### ISSUE TITLE
Show all relevant domain classes for a property

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#453] opened 2024-01-31 15:52 UTC
This affects RDF/S properties,

Often  properties have >1 classes in their domain, for example:
```
dc:description a rdfs:Property ;
    rdfs:label "Description"@en ;
    rdfs:comment "An account of the resource."@en ;
    sdo:domainIncludes elm:Accreditation,
        elm:AwardingProcess,
        elm:Claim,
        elm:ContactPoint,
        elm:DisplayParameter,
        elm:GradingScheme,
        elm:Grant,
        elm:LearningAchievement,
        elm:LearningAchievementSpecification,
        elm:LearningActivity,
        elm:LearningActivitySpecification,
        elm:LearningAssessment,
        elm:LearningAssessmentSpecification,
        elm:LearningEntitlement,
        elm:LearningEntitlementSpecification,
        elm:LearningOpportunity,
        elm:MediaObject,
        elm:PriceDetail,
        elm:Qualification,
        elm:ResultDistribution,
        elm:Specification,
        elm:VerificationCheck,
        dc:Location .
```

I need DESM to show the classes that are relevant to the mapping being done (which in practice probably means showing all of them)

Instead DESM shows only one:
![image](https://github.com/t3-innovation-network/desm/assets/658047/70003305-8450-4005-bb07-28ddbb498c90)

(This image shows one example of where DESM shows the class for properties, when viewing a mapping, the same is also true during the mapping process)

**Comment by jeannekitchens** [comment] 2024-02-10 00:15
@philbarker agree with moving this to priority 1.  DESM needs to show all classes a property has in their domain.  It is currently showing only 1 class that could be completely unrelate to the mapping making the mapping look nonsensical.

**Comment by philbarker** [comment] 2024-02-13 11:59
Suggested resolution: I think it is not entirely realistic to show all the classes all the time for all properties: some have more than in the screen shot above.  Many of them won't be relevant to the abstract class being considered. 
During the domain schema upload, the user is asked to select relevant classes, so use this info to decide which to show. 

- [ ] show the classes in the domain of the property (classes that comprise the property is part for JSON/XML and other schema types) that were selected as relevant during the schema upload.
- [ ] show the human readable compact URIs (as is the case now, e.g. dc:Location, elm:Claim)

**Comment by philbarker** [comment] 2024-04-18 14:13
Checked with CTDL on PhilQA profile for Organization Abstract Class. Mapped ceterms PostalAddress, CredentialOrganization, QACredentialOrganization and Organization to abstract class. Added alternateName, name, description and streetAddress properties. All displayed with relevant classes, e.g. name in all four classes, streetAddress only in PostalAddress:

![Image](https://github.com/t3-innovation-network/desm/assets/658047/93bf65c2-89e8-4d7e-8255-86d6a70a1a43)

All good, moving to QA passed.

**Comment by philbarker** [comment] 2024-05-30 15:50
@excelsior @edgarf  @shlag3n Bumping this back to In Progress because we have a reversion. Now when I repeat the process described here: https://github.com/t3-innovation-network/desm/issues/453#issuecomment-2063971150 I see


![Image](https://github.com/t3-innovation-network/desm/assets/658047/a5216709-3f32-4de0-bb85-9ca862c83ea4)


I noticed something like this in the CSV download but couldn't check because of the bug that was stopping me from marking mappings as done.

**Comment by excelsior** [comment] 2024-06-03 04:59
@philbarker The regression was caused by my #444 fix. I reconciled the two improvements, the page should look good again.

**Comment by philbarker** [comment] 2024-06-03 10:59
@excelsior looks fixed now, thanks.  Moved to QA passed.

**Closed** 2024-06-13 17:22 UTC
Labels: enhancement, Mapping UI
