### ISSUE TITLE
Not all relevant properties in uploaded schema are available

### ISSUE THREAD

**Issue by stuartasutton** [t3-innovation-network/desm#363] opened 2022-12-03 22:04 UTC
I've run into a problem that while in the midst of mapping, I realized I am missing a property that was present in the uploaded schema that was: (1) not caught in the parsed data; or (2) was selected by me but it didn't move over in the domain mapping batch; or (3) I just missed tagging it during the domain mapping.  Regardless of the reason it doesn't appear as a property to be mapped, I see no way to rectify the problem, no way to add a property once the crosswalking has begun. (Missing asn:statementLabel.)

**Comment by philbarker** [comment] 2022-12-05 12:24
There are issues in the schema file that probably stop `license` and `statementLabel` from being available.

I cannot reproduce the issue with `created`

**Comment by stuartasutton** [comment] 2022-12-08 14:56
There is another that is missing: modified (Date Modified)

**Comment by stuartasutton** [comment] 2022-12-08 15:00
Phil, can you describe the issues you found you found in the RDF/XML schema (https://github.com/t3-innovation-network/desm/issues/363#issuecomment-1337256459) preventing license and statementLabel that stop them from being available?

**Comment by stuartasutton** [comment] 2022-12-08 15:00
Phil, I may have passed over the modified property in my domain mapping (https://github.com/t3-innovation-network/desm/issues/363#issuecomment-1337256459). I have no way of knowing.

**Comment by stuartasutton** [comment] 2022-12-08 15:06
@philbarker, the issue for me now, is what do I do about these missing properties so I can finish. I see no way to add anything after the process of mapping has begun; i.e., how do I upload them mid-process? Do I create another RDF/XML that includes them correcting any issues you found for license and statementLabel and add the rdfs:Class statement you suggest for anyURI in https://github.com/t3-innovation-network/desm/issues/363#issuecomment-1337236877?  Is so, how do I get it into the tool?

**Comment by philbarker** [comment] 2022-12-08 16:14
> Phil, can you describe the issues you found you found in the RDF/XML schema ([#363 (comment)](https://github.com/t3-innovation-network/desm/issues/363#issuecomment-1337256459)) preventing license and statementLabel that stop them from being available?

So sorry @stuartasutton, I thought I had.  

In asnProfile.rdf I see
```
  <rdf:Property rdf:about="http://purl.org/ASN/schema/core/statementLabel">
    <rdfs:isDefinedBy rdf:resource="http://purl.org/ASN/schema/core/"/>
    <rdfs:comment>The textual label designating the class of statement in the structure of statements in the Standard Document--e.g., Standard, Benchmark, Strand, Topic, etc.</rdfs:comment>
    <rdfs:domain rdf:resource="http://purl.org/ASN/schema/core/statement"/>
```
You need an upper case S for Statement in the domain URI

Similarly for `license`
```
  <rdf:Property rdf:about="http://purl.org/dc/terms/license">
    <rdfs:domain rdf:resource="http://purl.org/ASN/schema/core/standardDocument"/>
```
should be **S**tandardDocument in the URL.

You should check that the domain for `modified` has the classes you imported (I see  LearningResource and RightsAndAttribution but not, e.g. Statement.

>  what do I do about these missing properties so I can finish.
Yes, please try creating another RDF/XML and importing the missing properties from that. If that doesn't work let me know, you may have to "complete" without them.

**Comment by stuartasutton** [comment] 2022-12-08 16:26
Thanks, Phil. Will follow through.

**Comment by excelsior** [comment] 2022-12-13 09:19
@philbarker Your assumption is correct. When the user uploads a file, the tool looks for domain defined in the file and allows them to choose the domains they'd like to proceed with. Then it builds a specification containing only the terms belonging to the selected domains.

Should extraneous classes (e.g. `anyURI`) be included into the list of selectable domains?

**Comment by stuartasutton** [comment] 2022-12-13 19:30
Not yet. On my agenda.

**Comment by philbarker** [comment] 2022-12-16 17:56
The fix currently deployed on staging correctly identifies the classes in the domain but not described in the file, and imports properties from these. So far so good. 

I does not close this issue because it does not deal with the last bit:
>   If no domain is declared for a property then rdfs:Resource is the de facto default (full URI is http://www.w3.org/2000/01/rdf-schema#Resource )

Nor does it deal with issue #346 

Here's a (hopefully) self-documenting test case:

```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix test: <http://example.org/test/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

test:Human a rdfs:Class ;
    rdfs:label "Human" ;
    rdfs:comment "A Human, software programs, etc." .

test:SomethingElse a rdfs:Class ;
    rdfs:label "Something Else" ;
    rdfs:comment "Look at that, over there..." .


test:Control a rdfs:Property ;
    rdfs:domain test:Human ;
    rdfs:comment "All information about domain and class are present."@en ;
    rdfs:label "Control"@en .

test:NoClass a rdfs:Property ;
    rdfs:domain test:Corporation ;
    rdfs:comment "The class in the domain is not declared in this file."@en ;
    rdfs:label "No Class"@en .


test:NoDomain a rdfs:Property ;
    rdfs:comment "No Domain is declared, use rdfs:Resource."@en ;
    rdfs:label "No Domain"@en .
    
test:Irrelevant a rdfs:Property ;
    rdfs:comment "This should be ignored if Human is selected as Domain class."@en ;
    rdfs:label "Irrelevant"@en ;
    rdfs:domain test:SomethingElse ;
    rdfs:range test:Human .    
```

**Comment by stuartasutton** [comment] 2022-12-16 20:27
I can verify that the "rdfs:Resource is the de facto default" absolutely works and in no way violates any goal of the data model's intention behind not including a domain declaration.

**Comment by jbaird123** [comment] 2022-12-22 17:43
Completed.

**Closed by jbaird123** 2022-12-22 17:43 UTC
Labels: schema upload issues, blocker, Domain mapping
