### ISSUE TITLE
Enhancement: Displaying the domain and range of properties

### ISSUE THREAD

**Issue by stuartasutton** [t3-innovation-network/desm#365] opened 2022-12-05 18:18 UTC
I realize this is likely an enhancement, but it would be useful in the property display to include the domain and range of the property. With the ASN mapping, we have the abstract domain, "Competence" but could benefit a lot by adding: 

1. domain (e.g. in ASN, the abstract domain of "Competence" is expressed by two actual classes, "StandardDocument" and "Statement"; and
2. range 

For example:

Label: Date Valid
Property: valid
Domain: StandardDocument
Range: Literal

If this is thought to be too much for the average user, perhaps consider a 2-level display that can be toggled from "minimal" (current display) to "full" with all of the above.

**Comment by philbarker** [comment] 2024-05-08 11:31
We are moving towards this, I think we have better display of the "class" with which a property is associated coming.
The value type for a property is important information in deciding how it maps to others. Making priority 1.

**Comment by philbarker** [comment] 2024-07-01 13:47
@excelsior I'm surprised the list of domains is really long. Are you filtering to show only those that are relevant?

**Comment by excelsior** [comment] 2024-07-04 09:03
@philbarker Yes, the list is filtered. But the number of domains shown will be the same as on the Shared Mappings page, and some properties there have well more than one domain.

What do you think about displaying only one domain and range in the property card during the mapping process with an option to expand the list to show them all?

**Comment by philbarker** [comment] 2024-07-08 11:38
I don't see the domain/range etc when doing the mapping.

**Comment by philbarker** [comment] 2024-07-10 17:48
Looks good with the "expand" option, shows the right values. Thank you.

**Comment by AH1CEDS** [comment] 2024-07-15 17:23
@edgarf , 
1) The following functionalities work fine on the “Align and Fine Tune” page: 

- 	Allow expanding property cards individually
-	Display domains and ranges in term cards
- 	Only show property domains selected during upload


2) “Hide domains and ranges on _non-mapping_ pages” – I do not see domains and ranges on the “Map to Domains” page. Perhaps, this is by design. If the “Map to Domains” page is considered a _non-mapping_ page (despite its name) since here we are only adding the properties and not matching them, then it is ok as is.

![image](https://github.com/user-attachments/assets/39b9e727-e356-4d22-80bf-d68b0c801635)


3) On May 28, 2024 Phil commented that “The relevant domain and the range (or expected value data type) ... should be displayed wherever property mappings are displayed (i.e. during the property mapping process and when **displaying completed mappings**). … displaying the mappings **includes the CSV download**.”

When I download the CSV for the test mapping I created (https://tool.desmsolutions.org/mappings-list?abstractClass=Person&cp=19), the domains/classes of the mapped terms are there (column “Mapped term class/type”) and match the class/type displayed on the view mapping page (yellow highlighted). At the same time, the ranges (green highlighted) are not included in the CSV. Now, per #398, the ranges column is _not_ listed as a required column, so the CSV seems fine in that regard. There just seems to be a contradiction to the request above to include the range in the completed mapping, which includes the CSV download. If I am misunderstanding the request, and the ranges are _not_ expected to be included in the CSV, then it is ok as is.

![image](https://github.com/user-attachments/assets/e838e4f9-2027-43d6-a478-329b84731e6d)
![image](https://github.com/user-attachments/assets/e21738f7-02a7-4e67-b919-840a07d201d6)

**Comment by excelsior** [comment] 2024-07-17 17:19
@AH1CEDS,

Since the [comment](https://github.com/t3-innovation-network/desm/issues/365#issuecomment-2134808158) requiring to display ranges in the CSV downloads postdates #398, I decided to include ranges alongside domains. The change is available on gopher.

**Comment by philbarker** [comment] 2024-08-01 13:38
Looks good on Credential Engine, we can close this

**Closed** 2024-08-22 19:12 UTC
Labels: enhancement, Property mapping, listed on DESM report, Mapping UI
