### ISSUE TITLE
Mapping UI Usability Issues

### ISSUE THREAD

**Issue by jeannekitchens** [t3-innovation-network/desm#376] opened 2022-12-07 14:42 UTC
From @siuc-nate

It is not obvious that the comment field becomes available after selecting an alignment.  The functionality of the drop-down box should not change like this. I didn't stumble across this until I went back to try to change an alignment.
Also, the box itself stops responding to clicks after an alignment is selected; you must instead click exactly on the arrow on the right.
There should be a separate text field for adding comments, and the functionality of the drop-down list should be consistent no matter its value.

![image](https://user-images.githubusercontent.com/20917206/206208518-8726e9de-1b88-4a22-9c43-4bccae8bc6be.png)

**Comment by philbarker** [comment] 2024-02-09 15:43
I would like to see the comments separate from the selection of the alignment predicate, and for the behaviour of the alignment selection box not change.
We need to consider this in conjunction with how to add information about data transformations #448 so no solution yet

**Comment by edgarf** [comment] 2024-05-29 19:43
@philbarker I'm moving this task to Ready column, hope you are OK with it.

**Comment by philbarker** [comment] 2024-06-13 10:28
Tested on PhilQA, here is what the pop-up looks like

![Image](https://github.com/t3-innovation-network/desm/assets/658047/306eb7d1-bfc5-4a43-90d8-5fccd39b11bb)

Looks great!

**Comment by AH1CEDS** [comment] 2024-07-15 18:02
@edgarf , The comment box looks good and functions as intended. The comments are included in the exported mapping files as expected.

**“No Match” predicate scenario:** One additional note on a possible enhancement and/or a comment to add to the documentation: If a user goes to edit a mapping and changes a predicate on the “Align and Fine Tune” page for a previously mapped term to use the “No Match” predicate, then the mapped term is dropped from the mapping. This is logical as “no match” implies that there should not be a mapped term. However, a user can then manually drag the term back into its place, save the mapping, and export the incongruent result. Consider disabling the ability to add a mapped term when “No Match” is selected and/or adding a warning.

![image](https://github.com/user-attachments/assets/dab3b2bb-7b9d-44ee-9e3b-aa0e79f13a11)
![image](https://github.com/user-attachments/assets/8484ae68-2396-49f0-953f-8d1dcd781c0d)

The comment box already handles this scenario correctly as it doesn't show the mapped term:
![image](https://github.com/user-attachments/assets/13803ed1-def2-4bef-947e-b6771fa926d0)

**Comment by excelsior** [comment] 2024-07-17 18:52
@AH1CEDS,

Good catch! I disabled dropping terms on alignments with the `No Match` predicate.

**Comment by dlawsonQIP** [comment] 2024-07-19 19:48
Verified on Gopher staging...mapped term does not display when predicate is "No Match"

**Comment by philbarker** [comment] 2024-08-01 13:46
Looks good on Cred Eng.

**Closed** 2024-08-22 19:12 UTC
Labels: enhancement, Property mapping, Usability, listed on DESM report, Mapping UI
