### ISSUE TITLE
Logged in Users Cannot Access Publicly Shared Mappings

### ISSUE THREAD

**Issue by jeannekitchens** [t3-innovation-network/desm#473] opened 2024-03-05 18:07 UTC
If you're an administrator or a mapper and are logged into DESM and select the "View Mappings" link, you get a blank page.  This really should be corrected.  It would have to be a bug.  There's no substantiation for not being able to see this page if you're logged in.   This should be taken care of when doing the tranche of updates to the public page. 

![image](https://github.com/t3-innovation-network/desm/assets/20917206/b23ff67a-d2d9-40e6-8572-08df92440346)
![image](https://github.com/t3-innovation-network/desm/assets/20917206/b64b966a-3218-4ffc-8849-98b569be5042)

**Comment by philbarker** [comment] 2024-03-06 10:47
related: #454

**Comment by philbarker** [comment] 2024-03-11 18:13
The current behaviour is quite odd; sometimes an admin user cannot see any mappings, sometimes they go straight to the last one they were looking at when not logged in without being given a choice. See this video https://www.pjjk.net/temp/DESMVids/simplescreenrecorder-2024-03-11_18.04.52.mkv

Suggested solution:
- [ ] Anyone who is logged in should be able to view the same choice of shared mappings as users who are not logged in. 
- [ ] For all users, clicking on the View Shared Mappings button should go to the same page (offering a choice of mappings) whenever they click it.

**Comment by philbarker** [comment] 2024-05-13 14:19
@shlag3n  This part isn't working:
- For all users, clicking on the View Shared Mappings button should go to the same page (offering a choice of mappings) whenever they click it.

Steps to reproduce: 
1. log in as mapping user in a profile for which there is a shared mapping (e.g. phil+ceds)
2. click on "view shared mappings"
- observed behaviour: you are taken to a screen showing the mapping for that user/profile (with an easily missed option to change mapping at the top)
- expected behaviour: you go to a screen giving you the option of viewing any/all shared mappings, same as anyone else.
Possible related:
if at step 1 you log in as a mapping user with no shared mappings, there is a message saying no shared mappings found for requested configuration profile:


![Image](https://github.com/t3-innovation-network/desm/assets/658047/2f121f0d-727f-4b5f-bc31-7fff76e30373)

Moving back to In progress. Let me know if there is any difficulty in implementing this as requested, because I think we could live with what you have implemented for now.

**Comment by philbarker** [comment] 2024-05-27 14:19
Works as expected, moving to QA passed

Thank you @shlag3n

**Closed** 2024-06-13 17:23 UTC
Labels: Viewing mapping
